# development:
#   access_key_id: ENV['AWS_ACCESS_KEY_ID']
#   secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
#   bucket: ENV['S3_AVATAR_BUCKET']
#   #ssl_ca_file: /opt/local/share/curl/curl-ca-bundle.crt
# test:
#   access_key_id: ENV['AWS_ACCESS_KEY_ID']
#   secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
#   bucket: ENV['S3_AVATAR_BUCKET']
#   #ssl_ca_file: /opt/local/share/curl/curl-ca-bundle.crt
# production:
#   access_key_id: ENV['AWS_ACCESS_KEY_ID']
#   secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
#   bucket: ENV['S3_AVATAR_BUCKET']